"""The built-in :class:`TemplatedCustomScaffold` plugin.

This is the engine's main contribution: a :class:`CustomScaffold` that
reads a ``fluid-scaffold.yaml`` manifest + Jinja templates from disk and
produces ``write_file`` actions. Bundle authors who don't want to write
Python just ship YAML + templates; this plugin does the rest.

Used by:

* The CLI when a user binds an npm/git/path/pypi bundle in their
  contract (the engine resolves the bundle, then instantiates this class
  pointed at the resolved bundle root).
* Anyone programmatically generating scaffolds from a local bundle dir
  (``TemplatedCustomScaffold(bundle_root=..., pattern_name=...)``).

This class is also registered as a Provider under
``fluid_build.providers`` so the FLUID CLI's plugin-listing surface
shows it.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List, Mapping, Optional

from fluid_sdk import (
    CustomScaffold,
    PluginError,
    PluginMetadata,
    write_file_action,
)

from .context import build_render_context
from .manifest import BundleManifest, PatternEntry
from .renderer import Renderer
from .version import ENGINE_VERSION


class TemplatedCustomScaffold(CustomScaffold):
    """A :class:`CustomScaffold` driven by a ``fluid-scaffold.yaml`` manifest.

    Construction parameters:

    * ``bundle_root`` — path to a resolved bundle directory containing
      ``fluid-scaffold.yaml`` + templates/.
    * ``pattern_name`` — which pattern within the bundle to invoke.
    * ``variables`` — user-supplied variable overrides.
    * ``output_root`` — destination root for the generated files
      (inherited from :class:`CustomScaffold`).
    """

    name = "templated-custom-scaffold"

    def __init__(
        self,
        *,
        bundle_root: Path,
        pattern_name: str,
        variables: Optional[Mapping[str, Any]] = None,
        output_root: Optional[Path] = None,
        **kwargs: Any,
    ) -> None:
        super().__init__(output_root=output_root, **kwargs)
        self.bundle_root = Path(bundle_root).resolve()
        self.pattern_name = pattern_name
        self.variables: Dict[str, Any] = dict(variables or {})

        self._manifest = BundleManifest.from_path(self.bundle_root)
        self._pattern = self._manifest.get_pattern(pattern_name)
        if self._pattern is None:
            raise PluginError(
                f"bundle {self._manifest.bundle.name!r} has no pattern named "
                f"{pattern_name!r} (available: {self._manifest.pattern_names()})"
            )

        self._renderer = Renderer(self.bundle_root)

    # ── plugin metadata ─────────────────────────────────────────────

    @classmethod
    def get_plugin_info(cls) -> PluginMetadata:
        return PluginMetadata(
            name=cls.name,
            role=cls.role,
            display_name="Templated Custom-Scaffold (built-in)",
            description=(
                "Engine's built-in CustomScaffold for YAML/Jinja bundles. "
                "Reads fluid-scaffold.yaml + templates, emits write_file actions."
            ),
            version=ENGINE_VERSION,
            author="FLUID community",
            tags=["scaffold", "templated", "engine-builtin"],
        )

    # ── plan: validate, build context, render, build actions ────────

    def plan(self, contract: Mapping[str, Any]) -> List[Dict[str, Any]]:
        # 1. Validate required contract fields up front — fail fast.
        self._check_required_fields(contract, self._pattern)

        # 2. Build the render context. Surface the bundle's own identity
        #    (name, version, author, description) under ``bundle`` so
        #    templates can reference it — useful for "generated by X
        #    v.Y" headers in output files.
        bundle = self._manifest.bundle
        bundle_ctx = {
            "name": bundle.name,
            "version": bundle.version,
            "description": bundle.description,
            "author": bundle.author,
            "license": bundle.license,
            "url": bundle.url,
            "pattern_name": self.pattern_name,
        }
        ctx = build_render_context(
            contract,
            variables=self.variables,
        )
        # Bundle context goes under a reserved key — user `variables`
        # could otherwise clobber it. Set after build_render_context so
        # `variables` doesn't override the bundle identity.
        ctx["bundle"] = bundle_ctx

        # 3. Render every template entry into RenderedFile records.
        rendered = self._renderer.render_pattern(self._pattern, ctx)

        # 4. Convert to write_file actions, sorted for determinism.
        rendered_sorted = sorted(rendered, key=lambda r: r.path)
        actions: List[Dict[str, Any]] = []
        for r in rendered_sorted:
            actions.append(
                write_file_action(
                    path=r.path,
                    content=r.content,
                    mode=r.mode,
                    description=r.description or None,
                ).to_dict()
            )
        return actions

    # ── helpers ─────────────────────────────────────────────────────

    @staticmethod
    def _check_required_fields(
        contract: Mapping[str, Any],
        pattern: PatternEntry,
    ) -> None:
        """Fail-fast presence check on ``pattern.required_contract_fields``.

        Each entry is a dotted path; ``labels["x"]`` syntax is supported.
        Wildcards (``*``) iterate over dict keys; trailing ``[]`` requires
        a non-empty list.
        """
        for required in pattern.required_contract_fields:
            if not _path_resolves(contract, required):
                raise PluginError(
                    f"Pattern {pattern.name!r} requires contract field "
                    f"{required!r}, which is missing or empty."
                )


# ---------------------------------------------------------------------------
# Cheap dotted-path resolver (supports ``labels["foo.bar"]`` and ``*``)
# ---------------------------------------------------------------------------


def _path_resolves(obj: Any, path: str) -> bool:
    """Return True if *path* resolves to a non-empty value in *obj*.

    Path syntax::

        metadata.owner.email
        metadata.labels["principal.steward.id"]
        environments.*.metadata.labels["cloud.accountId"]
        observability.alert.channels[]

    Wildcards (``*``) require *at least one* element to satisfy the rest
    of the path. Trailing ``[]`` requires a non-empty list.
    """
    tokens = _tokenize(path)
    return _resolve_tokens(obj, tokens)


def _tokenize(path: str) -> List[str]:
    """Split a dotted path into atomic tokens.

    ``metadata.labels["foo.bar"].baz`` → ``["metadata", "labels", "foo.bar", "baz"]``
    """
    tokens: List[str] = []
    i = 0
    cur = ""
    while i < len(path):
        ch = path[i]
        if ch == ".":
            if cur:
                tokens.append(cur)
                cur = ""
            i += 1
        elif ch == "[":
            if cur:
                tokens.append(cur)
                cur = ""
            j = path.find("]", i)
            if j == -1:
                raise ValueError(f"unterminated bracket in path: {path!r}")
            inner = path[i + 1 : j].strip()
            if inner == "":
                tokens.append("[]")
            else:
                tokens.append(inner.strip("\"'"))
            i = j + 1
        else:
            cur += ch
            i += 1
    if cur:
        tokens.append(cur)
    return tokens


def _resolve_tokens(obj: Any, tokens: List[str]) -> bool:
    if not tokens:
        return _is_present(obj)

    head, rest = tokens[0], tokens[1:]

    if head == "[]":
        # Require a non-empty list, then satisfy the rest against at
        # least one element.
        if not isinstance(obj, list) or not obj:
            return False
        if not rest:
            return True
        return any(_resolve_tokens(item, rest) for item in obj)

    if head == "*":
        if isinstance(obj, Mapping):
            return any(_resolve_tokens(v, rest) for v in obj.values())
        if isinstance(obj, list):
            return any(_resolve_tokens(item, rest) for item in obj)
        return False

    if isinstance(obj, Mapping):
        if head not in obj:
            return False
        return _resolve_tokens(obj[head], rest)

    return False


def _is_present(val: Any) -> bool:
    """Empty string / empty list / None counts as missing."""
    if val is None:
        return False
    if isinstance(val, str) and not val.strip():
        return False
    if isinstance(val, (list, dict)) and not val:
        return False
    return True
